;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Weapon.Aim",DevComment="")
+GameplayTagList=(Tag="Ability.Weapon.Fire",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Damage.FallDamage",DevComment="")
+GameplayTagList=(Tag="State.Aiming",DevComment="")
+GameplayTagList=(Tag="State.Armed",DevComment="")
+GameplayTagList=(Tag="Weapon.Pistol",DevComment="")
+GameplayTagList=(Tag="Weapon.Rifle",DevComment="")
+GameplayTagList=(Tag="Weapon.Unarmed",DevComment="")

